services:
  mealie:
    image: hkotel/mealie:v3.19.2@sha256:f68e959bf66f4f458893ea58facac71690fe6f2ac7a31466b5cecb41b4e99c02
    container_name: mealie
    networks:
      - proxy
    volumes:
      - "./data:/app/data"
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - "traefik.http.routers.mealie.rule=Host(`mealie.${FULL_DOMAIN}`)"
      - "traefik.http.routers.mealie.entrypoints=https"
      - "traefik.http.routers.mealie.tls=true"
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
      - DB_ENGINE=sqlite
      - "BASE_URL=https://mealie.${FULL_DOMAIN}"
    restart: unless-stopped

networks:
  proxy:
    external: true