repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.12.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        verbose: true
  - repo: https://github.com/dinoschristou/ansible-encyption-check.git
    rev: v0.1.0
    hooks:
      - id: ansible-encryption-check
