---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  vars_files:
    - vars/vault.yaml
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: techno_tim.k3s_ansible.prereq
      become: true
    - role: techno_tim.k3s_ansible.download
      become: true
    - role: techno_tim.k3s_ansible.raspberrypi
      become: true
    - role: techno_tim.k3s_ansible.k3s_custom_registries
      become: true
      when: custom_registries

- name: Setup k3s servers
  hosts: master
  vars_files:
    - vars/vault.yaml
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: techno_tim.k3s_ansible.k3s_server
      become: true

- name: Setup k3s agents
  hosts: node
  vars_files:
    - vars/vault.yaml
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: techno_tim.k3s_ansible.k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: master
  vars_files:
    - vars/vault.yaml
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: techno_tim.k3s_ansible.k3s_server_post
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: master
  vars_files:
    - vars/vault.yaml
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - name: Copying kubeconfig from {{ hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] }}
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: ./kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
