roles:
  - src: ironicbadger.docker_compose_generator
  - src: grog.package

collections:
  - name: ansible.utils
  - name: community.general
  - name: community.docker
  - name: ansible.posix
  - name: kubernetes.core
  - name: https://github.com/techno-tim/k3s-ansible.git
    type: git
    version: master
