---
- name: Setup main home servers
  hosts: proxmox_vms
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
  #  - grog.package
  #  - docker
   - docker_services

- name: Setup dns on piholes
  hosts: pihole-primary
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: pihole
     tags: dns

- name: Setup cloud servers
  hosts: cloud
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
  #  - grog.package
  #  - base
  #  - docker
   - docker_services
