---
- hosts: thorondor
  become: yes
  vars_files:
    - vars/vault.yaml
  roles:
    # - grog.package
    # - docker
    - docker-services

- hosts: piholes
  become: yes
  vars_files:
    - vars/vault.yaml
  roles:
    - role: pihole
      tags: dns 
