---
- name: Setup main home servers
  hosts: proxmox_vms
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
  #  - grog.package
  #  - base
  #  - docker
  #  - nfs_client
   - services

- name: Setup dns on piholes
  hosts:
   - pihole-primary
   - pihole-backup
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: pihole
     tags: dns

- name: Setup cloud servers
  hosts: cloud
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
  #  - grog.package
  #  - base
  #  - docker
  #  - docker_services
   - services

- name: Setup nut server
  hosts: pve3
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: nut_server
     tags: nut

- name: Setup nut clients
  hosts:
   - pve1
   - pve2
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: nut_client
     tags: nut_client

- name: Test new roles
  hosts: test_hosts
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: services
     tags: test
