---
- name: Setup docker services on thorondor
  hosts: thorondor
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
  # - grog.package
  # - docker
   - docker_services

- name: Setup dns on piholes
  hosts: pihole-primary
  become: true
  vars_files:
   - vars/vault.yaml
  roles:
   - role: pihole
     tags: dns
