version: "3"

tasks:
  encrypt:
    cmds:
      - ansible-vault encrypt vars/vault.yaml

  decrypt:
    cmds:
      - ansible-vault decrypt vars/vault.yaml

  ansible-reqs:
    cmds:
      - ansible-galaxy install -r requirements.yaml

  python-reqs:
    cmds:
      - pip install -r requirements.txt --user

  run:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns

  run-machine:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns --limit {{.CLI_ARGS}}

  update-dns:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags dns --limit piholes

  setup-ssh:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml playbooks/change-ssh-port.yml --limit {{.CLI_ARGS}}

  run-ext:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns --limit cloud

  nut-server:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags nut --limit pve3

  nut-client:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags nut_client --limit pve1,pve2

  config-only:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags config --limit {{.CLI_ARGS}}
