version: "3"

tasks:
  encrypt:
    cmds:
      - ansible-vault encrypt vars/vault.yaml

  decrypt:
    cmds:
      - ansible-vault decrypt vars/vault.yaml

  ansible-reqs:
    cmds:
      - ansible-galaxy install -r requirements.yaml

  python-reqs:
    cmds:
      - pip install -r requirements.txt --user

  run:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns

  run-machine:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns --limit {{.CLI_ARGS}}

  update-dns:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags dns --limit piholes

  setup-ssh:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml playbooks/change-ssh-port.yml --limit {{.CLI_ARGS}}

  run-ext:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --skip-tags dns --limit cloud

  nut-server:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags nut --limit pve3

  nut-client:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags nut_client --limit pve1,pve2

  config-only:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags config --limit {{.CLI_ARGS}}

  test-new-roles:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml site.yaml --tags test --limit test_hosts

  cluster-up:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml cluster-up.yaml

  cluster-down:
    cmds:
      - ansible-playbook -i inventory/hosts.yaml cluster-down.yaml

  new-config:
    cmds:
      - echo "Generating new configuration files in {{ .TASKFILE_DIR }}/configs"
      - mkdir -p {{ .TASKFILE_DIR }}/configs/{{.CLI_ARGS}}
      - cp {{ .TASKFILE_DIR }}/configs/ztemplate/docker-compose.yaml {{ .TASKFILE_DIR }}/configs/{{.CLI_ARGS}}/docker-compose.yaml
      - cp {{ .TASKFILE_DIR }}/configs/ztemplate/.env.st {{ .TASKFILE_DIR }}/configs/{{.CLI_ARGS}}/.env.st
