all:
  children:
    proxmox_vms:
      hosts:
        thorondor:
          ansible_host: 192.168.42.204
          ansible_user: ubuntu
        varda:
          ansible_host: 192.168.42.238
          ansible_user: ubuntu
    piholes:
      hosts:
        pihole-backup:
          ansible_host: 192.168.1.41
          ansible_user: pi
        pihole-primary:
          ansible_host: 192.168.3.237
          ansible_user: dinos
