all:
  children:
    proxmox_vms:
      hosts:
        mon:
          ansible_host: 192.168.60.44
        infra:
          ansible_host: 192.168.60.45
        mqtt:
          ansible_host: 192.168.42.122
        apps:
          ansible_host: 192.168.60.46
    unmanaged:
      hosts:
        ts:
          ansible_host: 192.168.42.166
    piholes:
      hosts:
        pihole-backup:
          ansible_host: 192.168.3.254
        pihole-primary:
          ansible_host: 192.168.1.202
    cloud:
      hosts:
        external-01:
          ansible_host: 192.168.92.60
          ansible_port: 4322
    proxmox_hosts:
      hosts:
        pve1:
          ansible_host: 192.168.42.57
          ansible_user: root
        pve2:
          ansible_host: 192.168.42.239
          ansible_user: root
