all:
  children:
    proxmox_vms:
      hosts:
        thorondor:
          ansible_host: 192.168.42.204
          ansible_user: ubuntu
        varda:
          ansible_host: 192.168.42.238
          ansible_user: ubuntu
        gondor:
          ansible_host: 192.168.42.225
          ansible_user: ubuntu
    piholes:
      hosts:
        pihole-primary:
          ansible_host: 192.168.3.237
          ansible_user: dinos
    cloud:
      hosts:
        external-test:
          ansible_host: 192.168.42.226
          ansible_user: ubuntu
          ansible_port: 4322
    proxmox_hosts:
      hosts:
        pve1:
          ansible_host: 192.168.42.57
          ansible_user: root
        pve2:
          ansible_host: 192.168.42.8
          ansible_user: root
        pve3:
          ansible_host: 192.168.42.9
          ansible_user: root
