all:
  children:
    proxmox_vms:
      hosts:
        thorondor:
          ansible_host: 192.168.42.204
          ansible_user: ubuntu
        varda:
          ansible_host: 192.168.42.238
          ansible_user: ubuntu
        gondor:
          ansible_host: 192.168.42.225
          ansible_user: ubuntu
        earendil:
          ansible_host: 192.168.42.191
          ansible_user: ubuntu
    piholes:
      hosts:
        pihole-backup:
          ansible_host: 192.168.3.254
          ansible_user: ubuntu
        pihole-primary:
          ansible_host: 192.168.1.202
          ansible_user: ubuntu
    cloud:
      hosts:
        # external-test:
        #   ansible_host: 192.168.42.226
        #   ansible_user: ubuntu
        #   ansible_port: 4322
        # oracle-cloud-vm1:
        #   ansible_host: 150.230.113.195
        #   ansible_user: ubuntu
        external-01:
          ansible_host: 192.168.92.60
          ansible_user: ubuntu
          ansible_port: 4322
    proxmox_hosts:
      hosts:
        pve1:
          ansible_host: 192.168.42.57
          ansible_user: root
        pve2:
          ansible_host: 192.168.42.8
          ansible_user: root
        pve3:
          ansible_host: 192.168.42.9
          ansible_user: root
    test_hosts:
      hosts:
        thorondor:
