---
- name: Restart ufw service
  become: true
  ansible.builtin.systemd:
    name: ufw
    state: restarted

- name: Restart fail2ban service
  become: true
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart ssh service
  become: true
  ansible.builtin.systemd:
    name: ssh
    state: restarted
