services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.14@sha256:1ec9b0c68297550c92f4a93feed432850c2993b261706cc3cc2e808f94a95e76
    container_name: filebrowser
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
    volumes:
      - /opt/knxcloud:/srv
      - ./database:/database
      - ./config:/config
    user: "1000:1000"
    command:
      - --database=/database/filebrowser.db
      - --root=/srv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${FULL_DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.middlewares=traefik-auth@docker"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
