services:
  stirlingpdf:
    image: frooodle/s-pdf:0.46.2
    networks:
      - proxy
    container_name: stirlingpdf
    volumes:
      - "./configs:/configs"
      - "./ocr-data:/usr/share/tesseract-ocr/5/tessdata"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.pdf.rule=Host(`pdf.${FULL_DOMAIN}`)"
      - "traefik.http.routers.pdf.entrypoints=https"
      - "traefik.http.routers.pdf.tls=true"
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
    env_file:
      - .env
      
networks:
  proxy:
    external: true