services:
  whoami:
    image: traefik/whoami@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: whoami
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${FULL_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"

networks:
  proxy:
    external: true
