services:
  whoami:
    image: traefik/whoami@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
    container_name: whoami
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${FULL_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"

networks:
  proxy:
    external: true
