services:
  portainer:
    image: portainer/portainer-ce:2.27.1
    container_name: portainer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${FULL_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
    driver: local
    name: portainer_data

networks:
  proxy:
    external: true
