services:
 postgres:
    image: postgres:15-alpine
    container_name: postgres
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:

  adminer:
    image: adminer:4.17.1
    container_name: adminer
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8082:8080
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${FULL_DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=https"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

volumes:
  pg_data:
    driver: local
    name: pg_data
networks:
  proxy:
    external: true