services:
  postgres:
    image: postgres:15-alpine@sha256:df7bca0066e6f60cc3dd32faa70caddec20e2c22b58932f79498e5704b23854a
    container_name: postgres
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
    labels:

  adminer:
    image: adminer:5.4.2@sha256:af4b73ddc41b7f7bb5e614eef1f35ba998307be2c8d1c54bf4890e8b946c6e67
    container_name: adminer
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8082:8080
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.${FULL_DOMAIN}`)"
      - "traefik.http.routers.adminer.entrypoints=https"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

volumes:
  pg_data:
    driver: local
    name: pg_data
networks:
  proxy:
    external: true