services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

networks:
  proxy:
    external: true