enable_monitoring_server: true
enable_db_server: true
enable_monitoring_target: true
enable_proxy: true
enable_portainer: true
enable_linkding: true
enable_authentik: true
enable_productivity: true
enable_rss: true
enable_glowprom: true

full_domain: "a.{{ hostname_root }}"
