enable_monitoring_server: true
enable_db_server: true
enable_monitoring_target: true
enable_proxy: true
enable_portainer: true
enable_linkding: true
enable_authentik: true
enable_productivity: true
enable_glowprom: true
enable_scrypted: false
enable_dashboard: true
enable_homebridge: false

full_domain: "main.{{ hostname_root }}"
