- name: Install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true
  become: true
  when: is_vm

- name: Systemd service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
  become: true
  when: is_vm
