{
 "title": "Glowprom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "24h Electricity Import",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_day_Wh{type=\"electric\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7d Electricity Import",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_day_Wh{type=\"electric\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30d Electricity Import",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_day_Wh{type=\"electric\"}[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24h Gas Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulative_Wh{type=\"gas\"}[24h])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "7d Gas Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulative_Wh{type=\"gas\"}[7d])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "30d Gas Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulative_Wh{type=\"gas\"}[30d])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "24h Gas Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulativevol_m3{type=\"gas\"}[24h])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "7d Gas Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulativevol_m3{type=\"gas\"}[7d])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "30d Gas Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(glowprom_import_cumulativevol_m3{type=\"gas\"}[30d])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "glowprom_power_W", "legendFormat": "Electricity" },
    {
     "expr": "increase(glowprom_import_cumulative_Wh{type=\"gas\"}[30m])",
     "legendFormat": "Gas"
    }
   ]
  },
  {
   "title": "Time Since Last Update",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - glowprom_timestamp{type=\"electric\"}",
     "legendFormat": "Electricity"
    },
    {
     "expr": "time() - glowprom_timestamp{type=\"gas\"}",
     "legendFormat": "Gas"
    }
   ]
  }
 ]
}