services:
  dozzle:
    image: amir20/dozzle:v10.6.15@sha256:5bb13e26b62f9bc4bd390e3e0c9423263b7df86e3a4167b718cc6e352f96b54f
    container_name: dozzle
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - DOZZLE_AUTH_PROVIDER=none
      - DOZZLE_LEVEL=info
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.${FULL_DOMAIN}`)"
      - "traefik.http.routers.dozzle.entrypoints=https"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.middlewares=traefik-auth@docker"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
