permit_join: false
mqtt:
  server: mqtt://192.168.42.122:1883
  user: "!secret user"
  password: "!secret password"
  client_id: MAIN_Z2M
  include_device_information: true
  keepalive: 60
  reject_unauthorized: false
serial:
  # Location of SLZB-06MU
  port: tcp://192.168.4.213:6638
  baudrate: 115200
  adapter: ember
  disable_led: false
frontend:
  port: 8080
  enabled: true
homeassistant:
  enabled: true
advanced:
  network_key: "!secret network_key"
  log_level: info
  transmit_power: 20
